services:
  verbacxss-website:
    container_name: "verbacxss-website"
    image: "verbacxss-website"
    build:
      context: "."
      args:
        BUILD_VERSION: ${BUILD_VERSION:-local}
    restart: "unless-stopped"
    ports:
      - "20000:20000"
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
